### ISSUE TITLE
error when yo meteor

### ISSUE THREAD

**Issue by luoweime** [Pent/generator-meteor#6]
_-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

[?] Shall we include Iron Router? Yes
[?] Shall we include Bootstrap with LESS? No
identical client/client.js
identical client/lib/subscriptions.js
identical client/views/home.js
identical client/views/home.html
identical client/views/common/loading.html
identical lib/collections.js
identical public/robots.txt
identical server/publications.js
identical server/server.js
identical server/security.js
identical .meteor/.gitignore
identical .meteor/release
identical .gitignore
identical LICENSE
identical README.md
identical client/routes.js
identical client/views/layout.html
identical client/styles/theme.css

fs.js:487
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EISDIR, illegal operation on a directory
    at Object.fs.readSync (fs.js:487:19)
    at module.exports (/usr/local/lib/node_modules/generator-meteor/node_modules/yeoman-generator/node_modules/isbinaryfile/index.js:14:21)
    at EventEmitter.collision (/usr/local/lib/node_modules/generator-meteor/node_modules/yeoman-generator/lib/util/conflicter.js:147:8)
    at /usr/local/lib/node_modules/generator-meteor/node_modules/yeoman-generator/lib/util/conflicter.js:57:18
    at /usr/local/lib/node_modules/generator-meteor/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /usr/local/lib/node_modules/generator-meteor/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/usr/local/lib/node_modules/generator-meteor/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at async.eachSeries (/usr/local/lib/node_modules/generator-meteor/node_modules/yeoman-generator/node_modules/async/lib/async.js:150:9)

**Comment by Pent** [comment]
I've updated dependency versions for node, yeoman, and other utilities. Not entirely sure the cause of this error but maybe the new dependencies will help.
